/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lijian_sf_im_sdk_IM_SDK */

#ifndef _Included_com_example_lijian_sf_im_sdk_IM_SDK
#define _Included_com_example_lijian_sf_im_sdk_IM_SDK
#ifdef __cplusplus
extern "C" {
#endif

 /* Class:     com_example_lijian_sf_im_sdk_IM_SDK
 * Method:    InitSDK
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT jint JNICALL Java_com_example_lijian_sf_1im_1sdk_IM_1SDK_InitSDK
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     com_example_lijian_sf_im_sdk_IM_SDK
 * Method:    ConnectMsgServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lijian_sf_1im_1sdk_IM_1SDK_ConnectMsgServer
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lijian_sf_im_sdk_IM_SDK
 * Method:    SendMsg
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_lijian_sf_1im_1sdk_IM_1SDK_SendMsg
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_lijian_sf_im_sdk_IM_SDK
 * Method:    ForbidSendMsg
 * Signature: (IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_lijian_sf_1im_1sdk_IM_1SDK_ForbidSendMsg
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jstring);

/*
 * Class:     com_example_lijian_sf_im_sdk_IM_SDK
 * Method:    DisonnServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lijian_sf_1im_1sdk_IM_1SDK_DisConnServer
  (JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_com_example_lijian_sf_1im_1sdk_IM_1SDK_ExitSDK
  (JNIEnv *, jobject);


/*
 * Class:     com_example_lijian_sf_im_sdk_IM_SDK
 * Method:    GetSyncServerTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lijian_sf_1im_1sdk_IM_1SDK_GetSyncServerTime
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lijian_sf_im_sdk_IM_SDK
 * Method:    GetServerTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_lijian_sf_1im_1sdk_IM_1SDK_GetServerTime
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lijian_sf_im_sdk_IM_SDK
 * Method:    OnIMCallbackListener
 * Signature: (Lcom/example/lijian/sf_im_sdk/OncallBackListener;)V
 */
/*JNIEXPORT void JNICALL Java_com_example_lijian_sf_1im_1sdk_IM_1SDK_OnIMCallbackListener
  (JNIEnv *, jobject, jobject);*/

#ifdef __cplusplus
}
#endif
#endif
